language: go
go:
- 1.9.2
env:
  global:
  - secure: "Q2a8XZdlW+Ykuygr8XL3v30tGHmARZdHbYFiSyQKQg1m7ftkfwen8C2HRGVue7lGNZvW0h8bNwxarBLe0FP+DL5XsRFoDUxpLaLVXQGZckwNZnXD/SJmF9kOfI+50cnoxu7EAyQP3A0XB8DGtcUlzC5ZZhfATZ0Rlu+VrRJph4YZf3UkpJQJA91m4sFcoRHpeDDrFHvN0DCldwACTO22FwUwsBXi2Hn1gtGKNESeZdwokOgD7GgkL6swNIXkmqHM82TfmRpdcnywjKG3JtMf5d8+AUbmakENS9R1XH/x9lw5ldND49B2SfbRwAVb7gCItOSt5tsMLOnOb3gfMEk/4xUfPRZeJbAIP0pXunIzbWB+E5am8JL/Gy/f9HI4R7IfumxX5X4SlBPT4ggG+no0nrBS+KOqKaQGi1yiBFR+Wn9l3/45RJXx7Kr0cbvO/yBdz5Hxodb8CC0rFGTTHAi4ALIW6HX/bIH5XzjgGv3YKSGuptCqmot2QFC/EfMSwfV6Sa0OyxpRxZz0FMGtXdRWQRl6H2W1ukXXvK2ithu/Z4HVNJrka8F/+Sh1IA+AkgHg30DFXWtsPi2gu7W8/0sdb6xwBXRV4btmdJcsnNTjOFEDH8WFJKYonhuSoXD1bsFq14w8w5Fy13FF6+6teA7ulOV9SGGzhuRpI2kpjrCUJZM="
  - GIT_DEPLOY_DIR=public
  - GIT_DEPLOY_BRANCH=master
  - GIT_DEPLOY_USERNAME="apettinen"
  - GIT_DEPLOY_EMAIL=antti.pettinen@gmail.com
branches:
  only:
  - sources
install:
- rm -rf public || exit 0
before_script:
- git config --global push.default simple
- git submodule init
- git submodule update
- git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
- go get github.com/kardianos/govendor
- govendor get github.com/gohugoio/hugo
- go install github.com/gohugoio/hugo
script:
- hugo
after_success:
- cp .travis.yml public
- bash deploy.sh -v
