language: go
go:
- 1.9.2
env:
  global:
  - GIT_DEPLOY_DIR=public
  - GIT_DEPLOY_BRANCH=master
  - GIT_DEPLOY_USERNAME="apettinen"
  - GIT_DEPLOY_EMAIL=antti.pettinen@gmail.com
  - secure: nW4mFfr1GEDxbNSMDU4npL5xfbIszG+T5laDNQCsw+NYx+NoE3ICuVXwjerBOMN1sgiH0knJYAjk+qT5OOIiSOn3OdV9HbMMXgs+fNiLPZ7iyWEtfMBM/O16Dgglk5tr8YV4n53v9zHweKtJh6I16JOePbcqQXNeRUegg1uYNgxenHR2zo5P3q0/pu11fGygQP0kjFUYTzlIkQhfBQYUqMJYKb/7924lL8PjDIxIR7mNeaQRyyQucN3e42nC8VOzTbGUONNi8WZrR+s+hyO25fSODJVWvaT6s5MeBcEffjV40aPFe6ebhtfQmD9BLnyE51IRfHgl+pmbjJD6AGYVyGPBapPbuXaxjKHk0TNwlQ0+GTdZZ3/u8K0IkRuyH/yjoXibww5qmaSJKmvQzqAfzCboJMvStk+Dq2LzVVsTD94vW7gwYrwzZn2oLTkbJeeMxRGktWb0i6IvqE2iJzx9dpOzYjpPjJZxj6MgwhOIqGGxQ2U0ehlReo/OGcdDITCrzduaLcO+lHQMkcjdIFYTLDJm0En3EAwGA/hPSbVcyvreFD6kMa2Z0FJE0X8v1lcfNuxvCLlnoujbuwKitifhb2AmZtl1KLRPW5RmeG7sHfK0x8emekgXjHu3zpO1glUQzzUjL584bEhHyYDf22XaTWx4+Y9uOlm77JZjSvBIJRA=
branches:
  only:
  - sources
install:
- rm -rf public || exit 0
before_script:
- git config --global push.default simple
- git submodule init
- git submodule update
- git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
- go get github.com/kardianos/govendor
- govendor get github.com/gohugoio/hugo
- go install github.com/gohugoio/hugo
script:
- hugo
after_success:
- cp .travis.yml public
- bash deploy.sh -v
