language: go
go:
- 1.9.2
env:
  global:
  - secure: f+Tn0v0mG9q5QJJn8u/V8K7MJaFLBqkitPzdAGU1PHRbmXRWQ1ihR9sD+v8XGsa7EceKjx9Mqzo0J3ImwB+HNGCOZiGVLzj+Gws7FViLW4z+2eetRUDnayDyQZl5hSm+rwauUnDwRVzCdUiyIe7ivs0VJqLTyi+l2E3EPT1sKRQLk57X8DUWmEupv6duejAeXkbWvSzrOG7VUZfyBQpcnZCJYCSIcppMTts0hXksABbW4DMekndTFhGsrqMCUEBRlFxMGe66lreh/rN9nPefcuxYgfweXkl6BcyASvy8EHZf6tIWcpjQy9H1wkhNx1KkiAnzStPTNrdBFSQCGbFgQhTxAjunGTe1Sno8Ml5KsnIBdxG/Z8eSyZX2rndKNamYNvqfvsQVun1KEvFpdDcfide6onYVB8RxLIi7jBiw7sPI0tbCb0atu+65WmMrHVrPkvKMBu0yyheGaYXs5uVRMdpMlxWgwT0xxU0tMmfooOD5hMnJ2rFBwqai0KDdM3DZBwSVL4O6qTRw9lmWWqUYgfRJrPtoZ00of4GdX5Xjdmf/fniepcrXD6D0A8NKkdRvLyqFIA2mZqrYBdzkYMHmY99ZqI3RUJyVFTAm2pX/LqE9gVDM7V2arCEXmuDbXQkDiMwD3qzE/eTytZGFvGF6j18XJ7y+l0B936fnoaxFBY4=
  - GIT_DEPLOY_DIR=public
  - GIT_DEPLOY_BRANCH=master
  - GIT_DEPLOY_USERNAME="apettinen"
  - GIT_DEPLOY_EMAIL=antti.pettinen@gmail.com
branches:
  only:
  - sources
install:
- rm -rf public || exit 0
before_script:
- git config --global push.default simple
- git submodule init
- git submodule update
- git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
- go get github.com/kardianos/govendor
- govendor get github.com/gohugoio/hugo
- go install github.com/gohugoio/hugo
script:
- hugo
after_success:
- cp .travis.yml public
- bash deploy.sh -v
