language: go

go:
  - "1.7.4"

env:
  global:
    - secure: "aSUBVXQP7d/PaUBlslmlenfhEgsLpHG9ei2pqcCpMyCZXCVm946gTeFiwfDtBXE/mHycow9VAE8PhHNl7nFVr2bMCvW5ZaF/aQikaTBDcuNDPrKn9oFmf5g+QHhRqSEQpAyh2SYRjRb82iykb7pcQ48/GGNl3Ap7jS9Z/zmpTZT12E10UmQ9GFpmkGt+TwHxznS5rdW4nTejkLZZ2cSyWyE1z5uUO6u8T6QqAIsw9hmP+MsG79z2ffcYXuiVaPwkW8rdxeq/HGK68uf0XLCQXheVmqbEr8RmbExI2YhfORNzidSOFuzgBFEu4vujn5g2xwjbwQTpkze2lgNhpfw59VlTI/jKP2KlnLJAttUlsP86K5jUXSRYG9+Ka7njFrron1l/Tc+fFUnzPxIj9STcd+5zk9oe586nUsxFqXK31urCpdJmKQ73ANUPMJIWyBKNAK9EBY+nVHmnVncP4T9VS2HYKPPwVoFDAZF9DNJAhno2Zy364ShTxETwd1ozlHnQxEbzfylrowowf2avdd1FcK7ibyBdS8NXTbcBjiWprp10fUoRRhS4S9f8HqAb7yyt4v6Et+Prtl2DLcmNt91/biqdEBk89THpz+6ER849549ydCzq+JNJNOOll7OkRPX9rGcqAgY2OpuHmd8lJ9xXNT3c5oDH2NJEQNViF76oIlI="
    - GIT_DEPLOY_DIR=public             # default output dir of Hugo
    - GIT_DEPLOY_BRANCH=master          # target branch
    - GIT_DEPLOY_USERNAME="MacAdminFi"   # dummy name
    - GIT_DEPLOY_EMAIL=antti.pettinen@gmail.com # replace by your email

branches:
  only:
    - sources                           # for Github Project Pages replace with "master"

install:
  - rm -rf public || exit 0             # cleanup previous run

before_script:
    #- git submodule init
    #- git submodule update
    - git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
    - go get -u -v github.com/spf13/hugo

script:
  #- binaries/hugo                       # Generate binaries
  - hugo
after_success:
  - cp .travis.yml public               # all branches need this file
  - bash deploy.sh -v                     # run the deploy
