languageCode = "en-us"
title = "MacAdmin.fi"
baseurl = "https://macadminfi.github.io/"
themesDir = "themes"
theme = "anybodyhome"
enableRobotsTXT = true
[Params]
  Subtitle = "Home of the Finnish Mac Admins"
  Author = "The Finnish MacAdmin Community"
