languageCode = "en-us"
title = "MacAdmin.fi"
baseurl = "http://macadmin.fi/"
themesDir = "themes"
theme = "anybodyhome"

[Params]
  Subtitle = "Home of the Finnish Mac Admins"
  Author = "The Finnish MacAdmin Community"
