languageCode = "en-us"
title = "MacAdmin.fi"
baseurl = "https://macadminfi.github.io"
themesDir = "themes"
theme = "hugo-theme-vec"
paginate = 10

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "post"
    weight = 0
    url = "/post"
  [[menu.main]]
    name = "contact"
    weight = 1
    url = "/contact"
  [[menu.main]]
    name = "about"
    weight = 2
    url = "/about"

[Params]
  Keywords = "macadminfi, finmacadmin"
  SelfIntro = "The Finnish MacAdmin Community"
  GithubID = "macadminfi"
  Avater = "img/finmacadmin2.png"
